languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
- "js/prototype/prototype.js"

engines:
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
